name: flutter_chat_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  chat:
    path: ./chat
  sqflite: ^2.4.0
  bloc: ^8.1.4
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  google_fonts: ^6.2.1
  http: ^1.2.2
  image_picker: ^1.1.2
  shared_preferences: ^2.3.2
  rethink_db_ns: ^0.0.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets:
    - assets/
